# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "qditnqwrjioypsuxwagg"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# The maximum number of connections the pooler will keep open with the upstream database.
# The pooler will scale the number of connections it keeps based on the traffic, but no more than
# pool_mode = "transaction"
# The maximum number of connections the pooler will keep open per user/database pair.
default_pool_size = 15
# Specifies when a server connection can be reused by other clients.
# Configure either `transaction` or `session` pooling.
# With `transaction` pooling, server connections are assigned to client connections only for the
# duration of a single transaction.
# For multi-statement transactions, `session` pooling is required.
pool_mode = "transaction"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will need to verify their email address before logging in.
enable_confirmations = true
# If enabled, users need to confirm any email change.
double_confirm_changes = true

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true

[auth.external.apple]
enabled = false
# Client ID for the Apple provider.
client_id = ""
# Secret for the Apple provider.
secret = ""

[auth.external.azure]
enabled = false
# Client ID for the Azure provider.
client_id = ""
# Secret for the Azure provider.
secret = ""

[auth.external.bitbucket]
enabled = false
# Client ID for the Bitbucket provider.
client_id = ""
# Secret for the Bitbucket provider.
secret = ""

[auth.external.discord]
enabled = false
# Client ID for the Discord provider.
client_id = ""
# Secret for the Discord provider.
secret = ""

[auth.external.facebook]
enabled = false
# Client ID for the Facebook provider.
client_id = ""
# Secret for the Facebook provider.
secret = ""

[auth.external.github]
enabled = false
# Client ID for the GitHub provider.
client_id = ""
# Secret for the GitHub provider.
secret = ""

[auth.external.gitlab]
enabled = false
# Client ID for the GitLab provider.
client_id = ""
# Secret for the GitLab provider.
secret = ""

[auth.external.google]
enabled = false
# Client ID for the Google provider.
client_id = ""
# Secret for the Google provider.
secret = ""

[auth.external.keycloak]
enabled = false
# Client ID for the Keycloak provider.
client_id = ""
# Secret for the Keycloak provider.
secret = ""

[auth.external.linkedin]
enabled = false
# Client ID for the LinkedIn provider.
client_id = ""
# Secret for the LinkedIn provider.
secret = ""

[auth.external.notion]
enabled = false
# Client ID for the Notion provider.
client_id = ""
# Secret for the Notion provider.
secret = ""

[auth.external.twitch]
enabled = false
# Client ID for the Twitch provider.
client_id = ""
# Secret for the Twitch provider.
secret = ""

[auth.external.twitter]
enabled = false
# Client ID for the Twitter provider.
client_id = ""
# Secret for the Twitter provider.
secret = ""

[auth.external.workos]
enabled = false
# Client ID for the WorkOS provider.
client_id = ""
# Secret for the WorkOS provider.
secret = ""

[functions]
# Limit for the number of functions that can be instantiated.

[functions.api_docs]
enabled = true

[functions.send-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false
