// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qditnqwrjioypsuxwagg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkaXRucXdyamlveXBzdXh3YWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODMzNzgsImV4cCI6MjA2Mjc1OTM3OH0.qY2jJb1qBP-jG3WdzCwAh8U4OW8rVL21frQ5ysr1bX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);